#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────
#  MTProto proxy installer (mtg v2.2.3)
# ─────────────────────────────────────────────

MTG_VERSION="2.2.3"
MTG_URL="https://github.com/9seconds/mtg/releases/download/v${MTG_VERSION}/mtg-${MTG_VERSION}-linux-amd64.tar.gz"
MTG_BIN="/usr/local/bin/mtg"
MTG_CONFIG_DIR="/etc/mtg"
MTG_CONFIG="${MTG_CONFIG_DIR}/config.toml"
MTG_SERVICE="/etc/systemd/system/mtg.service"

SNI="${1:-}"
PORT="${2:-}"

# ── Interactive prompts (if not passed as args) ─
if [[ -z "${SNI}" ]]; then
  read -rp "Домен маскировки [dl.google.com]: " SNI
  SNI="${SNI:-dl.google.com}"
fi

if [[ -z "${PORT}" ]]; then
  read -rp "Порт [5349]: " PORT
  PORT="${PORT:-5349}"
fi

# ── Colour helpers ─────────────────────────────
if [ -t 1 ] && command -v tput &>/dev/null && tput colors &>/dev/null 2>&1; then
  RED=$(tput setaf 1)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  CYAN=$(tput setaf 6)
  BOLD=$(tput bold)
  RESET=$(tput sgr0)
else
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  YELLOW='\033[0;33m'
  CYAN='\033[0;36m'
  BOLD='\033[1m'
  RESET='\033[0m'
fi

ok()   { echo -e "${GREEN}[✓]${RESET} $*"; }
err()  { echo -e "${RED}[✗]${RESET} $*" >&2; }
warn() { echo -e "${YELLOW}[!]${RESET} $*"; }
info() { echo -e "${CYAN}[→]${RESET} $*"; }

die() { err "$*"; exit 1; }

# ── 1. Root check ──────────────────────────────
if [[ $EUID -ne 0 ]]; then
  die "This script must be run as root. Try: sudo bash $0 $*"
fi
ok "Running as root"

# ── 2. Disable IPv6 ───────────────────────────
info "Disabling IPv6 at kernel level..."

SYSCTL_CONF="/etc/sysctl.conf"
declare -A IPV6_PARAMS=(
  ["net.ipv6.conf.all.disable_ipv6"]="1"
  ["net.ipv6.conf.default.disable_ipv6"]="1"
  ["net.ipv6.conf.lo.disable_ipv6"]="1"
)

for KEY in "${!IPV6_PARAMS[@]}"; do
  VAL="${IPV6_PARAMS[$KEY]}"
  if grep -q "^${KEY}" "${SYSCTL_CONF}" 2>/dev/null; then
    sed -i "s|^${KEY}.*|${KEY} = ${VAL}|" "${SYSCTL_CONF}"
  else
    echo "${KEY} = ${VAL}" >> "${SYSCTL_CONF}"
  fi
done

sysctl -p "${SYSCTL_CONF}" >/dev/null 2>&1 || warn "sysctl -p returned non-zero (may be okay in containers)"
ok "IPv6 disabled"

# ── 3. Download and install mtg ───────────────
info "Downloading mtg v${MTG_VERSION}..."

TMP_DIR=$(mktemp -d)
trap 'rm -rf "${TMP_DIR}"' EXIT

ARCHIVE="${TMP_DIR}/mtg.tar.gz"

if command -v curl &>/dev/null; then
  curl -fsSL "${MTG_URL}" -o "${ARCHIVE}" || die "Failed to download mtg"
elif command -v wget &>/dev/null; then
  wget -q "${MTG_URL}" -O "${ARCHIVE}" || die "Failed to download mtg"
else
  die "Neither curl nor wget found. Install one of them and retry."
fi

tar -xzf "${ARCHIVE}" -C "${TMP_DIR}"

# Find the binary inside the extracted directory
MTG_EXTRACTED=$(find "${TMP_DIR}" -type f -name "mtg" | head -1)
[[ -z "${MTG_EXTRACTED}" ]] && die "mtg binary not found in archive"

install -m 0755 "${MTG_EXTRACTED}" "${MTG_BIN}"
ok "mtg installed to ${MTG_BIN}"

# Sanity check
"${MTG_BIN}" --version &>/dev/null || die "mtg binary does not execute correctly"

# ── 4. Generate secret ────────────────────────
info "Generating fake-TLS secret for SNI: ${SNI}..."

SECRET=$("${MTG_BIN}" generate-secret --hex "${SNI}" 2>/dev/null) \
  || die "Failed to generate secret"

[[ -z "${SECRET}" ]] && die "Generated secret is empty"
ok "Secret generated"

# ── 5. Write config ───────────────────────────
info "Writing config to ${MTG_CONFIG}..."
mkdir -p "${MTG_CONFIG_DIR}"

cat > "${MTG_CONFIG}" <<TOML
# mtg configuration — generated by install-mtproto.sh
secret = "${SECRET}"

[network]
bind-to = "0.0.0.0:${PORT}"
prefer-ip = "prefer-ipv4"
TOML

ok "Config written"

# ── 6. Create systemd service ─────────────────
info "Creating systemd service..."

cat > "${MTG_SERVICE}" <<UNIT
[Unit]
Description=MTProto Proxy (mtg)
After=network.target
Documentation=https://github.com/9seconds/mtg

[Service]
Type=simple
User=nobody
ExecStart=${MTG_BIN} run ${MTG_CONFIG}
Restart=always
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadOnlyPaths=/
ReadWritePaths=${MTG_CONFIG_DIR}

[Install]
WantedBy=multi-user.target
UNIT

ok "Systemd service created"

# ── 7. Enable and start service ───────────────
info "Enabling and starting mtg service..."
systemctl daemon-reload
systemctl enable mtg
systemctl start mtg
ok "Service started (mtg.service)"

# ── 8. Open port in ufw ───────────────────────
if command -v ufw &>/dev/null && ufw status | grep -q "Status: active"; then
  info "Opening port ${PORT}/tcp in ufw..."
  ufw allow "${PORT}/tcp" >/dev/null
  ok "Port ${PORT} opened in ufw"
else
  warn "ufw is not active or not installed — skipping firewall rule"
  warn "Make sure port ${PORT}/tcp is reachable from the internet"
fi

# ── 9. Detect server IP ───────────────────────
info "Detecting server IP..."
SERVER_IP=$(curl -s --max-time 10 ifconfig.me 2>/dev/null || true)

if [[ -z "${SERVER_IP}" ]]; then
  warn "Could not detect public IP via ifconfig.me"
  SERVER_IP="<YOUR_SERVER_IP>"
fi
ok "Server IP: ${SERVER_IP}"

# ── 10. Summary ───────────────────────────────
TG_LINK="tg://proxy?server=${SERVER_IP}&port=${PORT}&secret=${SECRET}"

echo ""
echo -e "${BOLD}${CYAN}┌─────────────────────────────────────────────────────┐${RESET}"
echo -e "${BOLD}${CYAN}│           MTProto Proxy — Installation Summary      │${RESET}"
echo -e "${BOLD}${CYAN}├─────────────────────────────────────────────────────┤${RESET}"
printf "${BOLD}${CYAN}│${RESET}  %-20s ${GREEN}%-30s${RESET} ${BOLD}${CYAN}│${RESET}\n" "Server IP:"   "${SERVER_IP}"
printf "${BOLD}${CYAN}│${RESET}  %-20s ${GREEN}%-30s${RESET} ${BOLD}${CYAN}│${RESET}\n" "Port:"        "${PORT}"
printf "${BOLD}${CYAN}│${RESET}  %-20s ${GREEN}%-30s${RESET} ${BOLD}${CYAN}│${RESET}\n" "SNI domain:"  "${SNI}"
printf "${BOLD}${CYAN}│${RESET}  %-20s ${GREEN}%-30s${RESET} ${BOLD}${CYAN}│${RESET}\n" "Secret:"      "${SECRET}"
echo -e "${BOLD}${CYAN}├─────────────────────────────────────────────────────┤${RESET}"
echo -e "${BOLD}${CYAN}│${RESET}  ${BOLD}Telegram link:${RESET}"
echo -e "${BOLD}${CYAN}│${RESET}  ${GREEN}${TG_LINK}${RESET}"
echo -e "${BOLD}${CYAN}└─────────────────────────────────────────────────────┘${RESET}"
echo ""

warn "Keep your SECRET and SERVER IP private — do not share publicly."
warn "Anyone with the tg:// link can use your proxy."
echo ""
echo -e "${GREEN}${BOLD}MTProto proxy is up and running!${RESET}"
echo -e "Check status:  ${CYAN}systemctl status mtg${RESET}"
echo -e "View logs:     ${CYAN}journalctl -u mtg -f${RESET}"
